<a href="https://colab.research.google.com/github/Mercymerine/Machine_Learning_1/blob/main/knn_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [3]:
column_names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
column_names = [name.capitalize() for name in column_names]

In [4]:
adults = pd.read_csv('/content/adult_data', header=None, names=column_names)
adults.head()

Age          Workclass  Fnlwgt   Education  Education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital-status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital-gain  Capital-loss  Hours-per-week  Native-country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [5]:
adults.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Age             32561 non-null  int64 
 1   Workclass       32561 non-null  object
 2   Fnlwgt          32561 non-null  int64 
 3   Education       32561 non-null  object
 4   Education-num   32561 non-null  int64 
 5   Marital-status  32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Sex             32561 non-null  object
 10  Capital-gain    32561 non-null  int64 
 11  Capital-loss    32561 non-null  int64 
 12  Hours-per-week  32561 non-null  int64 
 13  Native-country  32561 non-null  object
 14  Income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [6]:
adults.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education-num     0
Marital-status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital-gain      0
Capital-loss      0
Hours-per-week    0
Native-country    0
Income            0
dtype: int64

In [7]:
adults.describe()

Age        Fnlwgt  Education-num  Capital-gain  Capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       Hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [8]:
adults.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education-num',
       'Marital-status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-country',
       'Income'],
      dtype='object')

In [9]:
adults['Capital-gain'].unique()

array([ 2174,     0, 14084,  5178,  5013,  2407, 14344, 15024,  7688,
       34095,  4064,  4386,  7298,  1409,  3674,  1055,  3464,  2050,
        2176,   594, 20051,  6849,  4101,  1111,  8614,  3411,  2597,
       25236,  4650,  9386,  2463,  3103, 10605,  2964,  3325,  2580,
        3471,  4865, 99999,  6514,  1471,  2329,  2105,  2885, 25124,
       10520,  2202,  2961, 27828,  6767,  2228,  1506, 13550,  2635,
        5556,  4787,  3781,  3137,  3818,  3942,   914,   401,  2829,
        2977,  4934,  2062,  2354,  5455, 15020,  1424,  3273, 22040,
        4416,  3908, 10566,   991,  4931,  1086,  7430,  6497,   114,
        7896,  2346,  3418,  3432,  2907,  1151,  2414,  2290, 15831,
       41310,  4508,  2538,  3456,  6418,  1848,  3887,  5721,  9562,
        1455,  2036,  1831, 11678,  2936,  2993,  7443,  6360,  1797,
        1173,  4687,  6723,  2009,  6097,  2653,  1639, 18481,  7978,
        2387,  5060])

In [10]:
adults['Capital-loss'].unique()

array([   0, 2042, 1408, 1902, 1573, 1887, 1719, 1762, 1564, 2179, 1816,
       1980, 1977, 1876, 1340, 2206, 1741, 1485, 2339, 2415, 1380, 1721,
       2051, 2377, 1669, 2352, 1672,  653, 2392, 1504, 2001, 1590, 1651,
       1628, 1848, 1740, 2002, 1579, 2258, 1602,  419, 2547, 2174, 2205,
       1726, 2444, 1138, 2238,  625,  213, 1539,  880, 1668, 1092, 1594,
       3004, 2231, 1844,  810, 2824, 2559, 2057, 1974,  974, 2149, 1825,
       1735, 1258, 2129, 2603, 2282,  323, 4356, 2246, 1617, 1648, 2489,
       3770, 1755, 3683, 2267, 2080, 2457,  155, 3900, 2201, 1944, 2467,
       2163, 2754, 2472, 1411])

Data Encoding

In [11]:
adults.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education-num',
       'Marital-status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-country',
       'Income'],
      dtype='object')

In [12]:
adults['Sex'].unique()

array([' Male', ' Female'], dtype=object)

In [13]:
adults['Sex'].replace([' Male', ' Female'], [0, 1], inplace=True)
adults.head()

Age          Workclass  Fnlwgt   Education  Education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital-status          Occupation    Relationship    Race  Sex  \
0        Never-married        Adm-clerical   Not-in-family   White    0   
1   Married-civ-spouse     Exec-managerial         Husband   White    0   
2             Divorced   Handlers-cleaners   Not-in-family   White    0   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black    0   
4   Married-civ-spouse      Prof-specialty            Wife   Black    1   

   Capital-gain  Capital-loss  Hours-per-week  Native-country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [14]:
adults['Income'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [15]:
adults['Income'].replace([' <=50K', ' >50K'], [0, 1], inplace=True)
adults.head()

Age          Workclass  Fnlwgt   Education  Education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital-status          Occupation    Relationship    Race  Sex  \
0        Never-married        Adm-clerical   Not-in-family   White    0   
1   Married-civ-spouse     Exec-managerial         Husband   White    0   
2             Divorced   Handlers-cleaners   Not-in-family   White    0   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black    0   
4   Married-civ-spouse      Prof-specialty            Wife   Black    1   

   Capital-gain  Capital-loss  Hours-per-week  Native-country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0  
4             0             0              40            Cuba       0

Performing one-hot encoding on categorical columns


In [16]:
adults_encoded = pd.get_dummies(adults, columns=['Workclass', 'Education', 'Marital-status', 'Occupation', 'Relationship', 'Race', 'Native-country'], drop_first=True)
adults_encoded = adults_encoded.astype(int)
adults_encoded.head()

Age  Fnlwgt  Education-num  Sex  Capital-gain  Capital-loss  \
0   39   77516             13    0          2174             0   
1   50   83311             13    0             0             0   
2   38  215646              9    0             0             0   
3   53  234721              7    0             0             0   
4   28  338409             13    1             0             0   

   Hours-per-week  Income  Workclass_ Federal-gov  Workclass_ Local-gov  ...  \
0              40       0                       0                     0  ...   
1              13       0                       0                     0  ...   
2              40       0                       0                     0  ...   
3              40       0                       0                     0  ...   
4              40       0                       0                     0  ...   

   Native-country_ Portugal  Native-country_ Puerto-Rico  \
0                         0                            0   
1                         0                            0   
2                         0                            0   
3                         0                            0   
4                         0                            0   

   Native-country_ Scotland  Native-country_ South  Native-country_ Taiwan  \
0                         0                      0                       0   
1                         0                      0                       0   
2                         0                      0                       0   
3                         0                      0                       0   
4                         0                      0                       0   

   Native-country_ Thailand  Native-country_ Trinadad&Tobago  \
0                         0                                0   
1                         0                                0   
2                         0                                0   
3                         0                                0   
4                         0                                0   

   Native-country_ United-States  Native-country_ Vietnam  \
0                              1                        0   
1                              1                        0   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   Native-country_ Yugoslavia  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 101 columns]

In [17]:
adults_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Columns: 101 entries, Age to Native-country_ Yugoslavia
dtypes: int64(101)
memory usage: 25.1 MB


Training and Testing Datasets

In [18]:
adults_encoded.columns

Index(['Age', 'Fnlwgt', 'Education-num', 'Sex', 'Capital-gain', 'Capital-loss',
       'Hours-per-week', 'Income', 'Workclass_ Federal-gov',
       'Workclass_ Local-gov',
       ...
       'Native-country_ Portugal', 'Native-country_ Puerto-Rico',
       'Native-country_ Scotland', 'Native-country_ South',
       'Native-country_ Taiwan', 'Native-country_ Thailand',
       'Native-country_ Trinadad&Tobago', 'Native-country_ United-States',
       'Native-country_ Vietnam', 'Native-country_ Yugoslavia'],
      dtype='object', length=101)

In [19]:
X=adults_encoded.drop('Income', axis=1)
y=adults_encoded['Income']
print(X.shape, y.shape)

(32561, 100) (32561,)


Modelling

KNN

In [20]:
knn = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))
scores = cross_val_score(knn, X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())

[0.82373714 0.82125307 0.81956388 0.8264742  0.82109951]
0.8224255608986148


In [ ]:
svm = make_pipeline(StandardScaler(), SVC(kernel='linear'))
scores = cross_val_score(svm, X, y, cv=5, scoring='accuracy')
print(scores)
print(scores.mean())